### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by nandorojo** [pacocoursey/use-descendants#3]
It's possible I messed something up, but I tried making the hello world from the Readme and got this error. Happened with 1.0.0-beta.4

CodeSandbox: https://codesandbox.io/s/angry-lederberg-k6i41?file=/src/App.js

<img width="1589" alt="Screen Shot 2021-07-12 at 8 03 24 PM" src="https://user-images.githubusercontent.com/13172299/125370343-39b33e80-e34c-11eb-9755-3bc1b0010f57.png">

Cool library idea! I can see it being really useful for composing dropdowns, autocompletes, etc.

**Comment by pacocoursey** [comment]
Hey sorry about that, I think I published the wrong version. `v1.0.0-beta.5` should be good to go

**Comment by pacocoursey** [comment]
Just noticed that it's broken on strict mode, forgot about the double rendering thing... will look into that.
